# Generated by Django 5.0.7 on 2024-08-05 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_parent_position_superior_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='subdivisions',
        ),
        migrations.AddField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='mainapp.subdivision'),
        ),
    ]
